export const AUTH_USER = "AUTH_USER";
export const UNAUTH_USER = "UNAUTH_USER"; 
export const AUTH_ERROR = "AUTH_ERROR";
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_SINGLE_USER = "FETCH_SINGLE_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const ACTIVATE_USER = "ACTIVATE_USER";
export const DEACTIVATE_USER = "DEACTIVATE_USER";
export const MAKE_USER_STAFF = "MAKE_USER_STAFF";
export const MAKE_USER_STUDENT = "MAKE_USER_STUDENT";
export const FETCH_CURRENT_USER_PROFILE = "FETCH_CURRENT_USER_PROFILE";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const AUTH_SUCCESS = "AUTH_SUCCESS";


export const FETCH_UNITS = "FETCH_UNITS";
export const CREATE_UNIT = "CREATE_UNIT";
export const EDIT_UNIT = "EDIT_UNIT";
export const DELETE_UNIT = "DELETE_UNIT";
export const CREATE_COMPLETION_UNIT = "CREATE_COMPLETION_UNIT";

export const FETCH_SESSIONS = "FETCH_SESSIONS";
export const CREATE_SESSION = "CREATE_SESSION";
export const EDIT_SESSION = "EDIT_SESSION";
export const DELETE_SESSION = "DELETE_SESSION";

export const FETCH_LESSONS = "FETCH_LESSONS";
export const CREATE_LESSON = "CREATE_LESSON";
export const EDIT_LESSON = "EDIT_LESSON";
export const FETCH_SESSION_LESSONS = "FETCH_SESSION_LESSONS";
export const FETCH_LESSON = "FETCH_LESSON";
export const DELETE_LESSON = "DELETE_LESSON";
export const FETCH_COMPLETED_LESSON = "FETCH_COMPLETED_LESSON";
export const CREATE_LESSON_COMPLETIONS = "CREATE_LESSON_COMPLETIONS";


export const FETCH_ALL_QUIZ = "FETCH_ALL_QUIZ";
export const CREATE_QUIZ = "CREATE_QUIZ";
export const DELETE_QUIZ = "DELETE_QUIZ";
export const CREATE_QUIZ_COMPLETIONS = "CREATE_QUIZ_COMPLETIONS";
export const FETCH_COMPLETED_QUIZZES = "FETCH_COMPLETED_QUIZZES";
export const FETCH_SINGLE_QUIZ = "FETCH_SINGLE_QUIZ";
export const CREATE_ANSWER = "CREATE_ANSWER";

export const FETCH_PUBLISHED_EXAMS = "FETCH_PUBLISHED_EXAMS";
export const FETCH_EXAMS = "FETCH_EXAMS";
export const CREATE_EXAM = "CREATE_EXAM";
export const DELETE_EXAM = "DELETE_EXAM";

export const FETCH_UNDONE_QUESTIONS = "FETCH_UNDONE_QUESTIONS";

export const CREATE_EXAM_QUESTION_STATUS = "CREATE_EXAM_QUESTION_STATUS";

export const FETCH_EXAM_QUESTION = "FETCH_EXAM_QUESTION";
export const FETCH_EXAM_ADMIN_QUESTION = "FETCH_EXAM_ADMIN_QUESTION";
export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const CREATE_EXAM_QUESTION = "CREATE_EXAM_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const PUBLISH_EXAM = "PUBLISH_EXAM";
export const UPDATE_EXAM_QUESTION_STATUS = "UPDATE_EXAM_QUESTION_STATUS";
export const EXAM_ERROR = EXAM_ERROR;

export const FETCH_QUESTION_RESPONSES = "FETCH_QUESTION_RESPONSES";
export const CREATE_ASSESSMENT_ESSAY_RESPONSE = "CREATE_ASSESSMENT_ESSAY_RESPONSE";
export const CREATE_RESPONSE = "CREATE_RESPONSE";
export const SUBMIT_EXAM_RESPONSES = "SUBMIT_EXAM_RESPONSES";

export const CREATE_EXAM_MARK = "CREATE_EXAM_MARK";
export const FETCH_ALL_EXAM_MARKS = "FETCH_ALL_EXAM_MARKS";

export const FETCH_ALL_ASSESSMENTS = "FETCH_ALL_ASSESSMENTS";
export const FETCH_UNIT_ASSESSMENTS = "FETCH_UNIT_ASSESSMENTS";
export const CREATE_ASSESSMENT = "CREATE_ASSESSMENT";
export const DELETE_ASSESSMENT = "DELETE_ASSESSMENT";
export const FETCH_SINGLE_ASSESSMENT_QUESTION = "FETCH_SINGLE_ASSESSMENT_QUESTION";
export const FETCH_SINGLE_ASSESSMENT_QUESTION_ADMIN = "FETCH_SINGLE_ASSESSMENT_QUESTION_ADMIN";
export const FETCH_ALL_ASSESSMENT_QUESTIONS = "FETCH_ALL_ASSESSMENT_QUESTIONS";
export const CREATE_ASSESSMENT_QUESTION_STATUS = "CREATE_ASSESSMENT_QUESTION_STATUS";

export const DELETE_ASSESSMENT_QUESTION = "DELETE_ASSESSMENT_QUESTION";
export const CREATE_ASSESSMENT_QUESTION = "CREATE_ASSESSMENT_QUESTION";
export const FETCH_ASSESSMENT_QUESTION_RESPONSES = "FETCH_ASSESSMENT_QUESTION_RESPONSES";
export const CREATE_ASSESSMENT_RESPONSE = "CREATE_ASSESSMENT_RESPONSE";

export const CREATE_ASSESSMENT_MARK = "CREATE_ASSESSMENT_MARK";
export const UPDATE_ASSESSMENT_QUESTION_STATUS = "UPDATE_ASSESSMENT_QUESTION_STATUS";
export const FETCH_ALL_ASSESSMENT_MARKS = "FETCH_ALL_ASSESSMENT_MARKS";
export const RETAKE_ASSESSMENT = "RETAKE_ASSESSMENT";

export const FETCH_SUMMARY = "FETCH_SUMMARY";

export const IN_CLASS_STAGE = "IN_CLASS_STAGE";
export const EXAM_COMPLETED_STAGE = "EXAM_COMPLETED_STAGE";
export const GRADUATED_STAGE = "GRADUATED_STAGE";
export const UNGRADUATED_STAGE = "UNGRADUATED_STAGE";
export const GENERATE_CERTIFICATE = "GENERATE_CERTIFICATE";
export const DELETE_CERTIFICATE = "DELETE_CERTIFICATE";
export const CREATE_USER_COMMENT = "CREATE_USER_COMMENT";

export const FETCH_ALL_ESSAYS = "FETCH_ALL_ESSAYS";
export const FETCH_SINGLE_ESSAY = "FETCH_SINGLE_ESSAY";
export const REVIEW_ESSAY = "REVIEW_ESSAY";


